### ISSUE TITLE
biom file not working with Phinch 

### ISSUE THREAD

**Issue by LeonardosMageiros** [smdabdoub/kraken-biom#12]
Hi, 

have analysed some metagenomic samples using Kraken2 and I would like to visualise my taxonomic profiles using Phinch (http://phinch.org).
I used kraken-biom to transform the kraken output to biom format but when I upload the files to Phinch the biom files are not eccepted by the software.

Have you ever faced this issue before?
I would appreceate any suggestions

Thank you in advance.

Best
Leonardos

**Comment by casperp** [comment]
Hi Leonardos,

I've faced this issue before. I did fix it it my [fork](https://github.com/casperp/kraken-biom) which still has to be merged @smdabdoub.  You can try to locally install that fork and use that version. ```pip install . ```

**Comment by heather340** [comment]
Hi Casper, 
I'm also having issues using the biom output in Phinch. Can you give me some more detail on how to work with your fork to reflect these fixes...? I'm working in a supercomputer system and just did 

pip install git+http://github.com/smdabdoub/kraken-biom.git 

to install kraken-biom. 

Thanks!
Heather

**Comment by smdabdoub** [comment]
Hi @heather340 and @casperp,

Apologies for taking so long to get on this. I've merged the metadata additions from @casperp, so that should resolve the problem!
