### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by rebeelouise** [smdabdoub/kraken-biom#13]
I have kraken2 outputs in the form of *.report and *.kraken

I am trying to make a biom file for phyloseq and would like some elaboration on the kraken_reports parameter? what is it for and how do you use it? 

I have generated a biom table from just the reports - however when reading the table into R I am missing taxa names.. 

Any help appreciated! 

Thanks

**Comment by smdabdoub** [comment]
Hi!

Thanks for the question. I have examples of the expected input files in my testing code. If you look in [test_process_samples.py] you will see what the format expected for the report files. But just to summarize, the program expects files containing the summarized counts per phylogenetic level. Let me know if that helps!

**Comment by marsfro** [comment]
Hello! I have the same question! Where is your  test_process_samples.py?

**Comment by marsfro** [comment]
> I have kraken2 outputs in the form of *.report and *.kraken
> 
> I am trying to make a biom file for phyloseq and would like some elaboration on the kraken_reports parameter? what is it for and how do you use it?
> 
> I have generated a biom table from just the reports - however when reading the table into R I am missing taxa names..
> 
> Any help appreciated!
> 
> Thanks

If you understand yet, please, help me too, I have the same problem for two weeks now

**Comment by smdabdoub** [comment]
Apologies, I thought I had linked it in my original reply. The correct link is below:

[test_process_samples.py](https://github.com/smdabdoub/kraken-biom/blob/master/test/test_process_samples.py)

**Comment by marsfro** [comment]
Thank you, I am trying
