### ISSUE TITLE
it will be great to share the testing examples

### ISSUE THREAD

**Issue by gc26762524** [smdabdoub/kraken-biom#8]
Hi, Thanks for your wonderful tool and it will be even better to share the S1.txt and S2.txt file as mentioned in the tutorial.  The output format from Kraken may vary so users may encounter confusion the exact input file format. Thank you!

Best,
Cheng

**Comment by smdabdoub** [comment]
Hi Cheng,

Apologies for just now getting back to you. The S1.txt and S2.txt are just example file names to give people and idea on how to run the program. However, if you look in the test folder, both [test_parsing.py](https://github.com/smdabdoub/kraken-biom/blob/master/test/test_parsing.py) and [test_process_samples.py](https://github.com/smdabdoub/kraken-biom/blob/master/test/test_process_samples.py) have examples of input files the program expects/can work with.
